# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Software Development Guidelines
author: INCF/OCNS Software SIG
logo: images/ocns_logo.png # To be added

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/OCNS/SoftwareDevelopmentGuidelines  # Online location of your book
  path_to_book: source
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  favicon: ""  # To be added
  google_analytics_id: "" # To be added
  home_page_in_navbar: false


# Extra parsing options
parse:
  myst_extended_syntax: true

